language: go
go:
- 1.x
script:
- go get -u
- mkdir -p build/linux
- GOOS=linux go build
- mkdir -p build/windows
- GOOS=windows go build
- mkdir -p build/darwin
- GOOS=darwin go build
sudo: false
before_deploy:
- echo "Deploying $TRAVIS_TAG to GitHub releases"
- cd build/linux && tar czf ccmd.linux.amd64.tar.gz * && cd -
- cd build/windows && tar czf ccmd.windows.amd64.tar.gz * && cd -
- cd build/darwin && tar czf ccmd.darwin.amd64.tar.gz * && cd -
deploy:
  provider: releases
  api_key:
    secure: fnPYHcnaijPVMtE7ePMW2elY6J1Z3se8NWtn4QBcjV5QZ8bdBVYNNa9GMu/HGChqI+AEiOIVpe+2+uyTUDSyWFvaIAVReVYBintBlfBS4A1L2TxSD+Cq/EcOPefPoEFEv9BzLycTk9zVoSJGKHXCaPvpDFmlDGjgP4/JELvsy5y8wokiYD9/nYKxxolBkr0jKjxhKhqsiBQ6IrWIFfmjTs73uTch1T4IJAkrdZZ4j8XgCLKC51D/7z6fEvjGi3Rgbd4NFpSjSQKbnbdEU1Syky1g3HHOII7GIEu8Ty6Wfi+N3xZ/veDr8jmPdpka6p2SSsRSDuttgwRVP421zCehrakDWO4EJ/Gic4WZ5CsT2k1ydymZZH6UMmkSBBhefmVnWRCCF4Ugh9V8Inpe/8KvmqCqb27Cnz/NrQhO4ecJQPG096fA8Sg53bIlqpolFFElm0wVAw0601Dp5/5QZ+txhzLHXOEmRaQ2hIw56foWdOZzOcHoob/b3SIS2syA0Qb/+D5llhnbkan9FcsqNbSSxQLNPjIgxM3/ZIK91REvExVWXncO7N40tqR/rVhCKN1EZ7levN02g3rBBOCpwfpsgczSAUlf9j7RgzeAqd3rnfO7hHTUCmTID9ltWoJnrGXprNBm7P1K2NYhMr02szsfTUULxWz1xtZblXMGOrEjmWY=
  file: build/*/*.tar.gz
  skip_cleanup: true
  on:
    repo: aestek/ccmd
    tags: true