language: go
go_import_path: github.com/shimmerglass/ccmd
go:
  - 1.x
script:
  - mkdir -p build/linux
  - env GO111MODULE=on GOOS=linux go build -o build/linux/ccmd
  - mkdir -p build/windows
  - env GO111MODULE=on GOOS=windows go build -o build/windows/ccmd.exe
  - mkdir -p build/darwin
  - env GO111MODULE=on GOOS=darwin go build -o build/darwin/ccmd
sudo: false
before_deploy:
  - echo "Deploying $TRAVIS_TAG to GitHub releases"
  - cd build/linux && tar czf ccmd.linux.amd64.tar.gz * && cd -
  - cd build/windows && tar czf ccmd.windows.amd64.tar.gz * && cd -
  - cd build/darwin && tar czf ccmd.darwin.amd64.tar.gz * && cd -
deploy:
  provider: releases
  api_key:
    secure: M8Vmm6ou9WRK8uIqppqZ0bmZczNrOmE3Q0UjiLL/pBwSj8l9MWVny9K1Ipid+g80nhMdusKlGHDQEHmCnz1BhYjr907htgjj+ZBx1A8HSaIuUlKtgtst0hF+qRbLZShoyTNvBnFW5IbeNkLlJz/4CG9sDTNtM5w6P9lHbHnqRmQzcENq8rppcgZuJgtQZsivuNUIyExt3ku8WXcwxG0e6f6HwhSuKH1ymA6ceBHnhaVNCHBV31sAu7aNO/aNAcc40KrVdQP24h0sPyZtVeueON3Iu9Gk3FruCCu8we9HEi5bWMWg1Bi0jcAyNK8N8U7yAK/PCrnaPgwPC/GVQU2beuNhL+wqglMMnybGL/pK30PzHxbNl36UzEUV0wpLgQQoQCyfMOtNgQtmVWvqUm7Rw0hTTo6VYkLFEA2xADEBQLXxL3zQ+M/sNIyqaICC8CfFfhlF62B2Oo8IOSh5PLsdgCZqXyoEQnluSl0fW/HnvNrO1eKyydzrN7NNV/+hFvgy+4AS3WgH2eJkSNaLPORMcRDB2koxsrsvdFBgG2pdM3wuVEveXKPPhCtQMDGF4RayR4SvU/werKKCCVJodHc2G4OQCFbSNPNbzbjwtuSoaeufiRyomwKUQWAjUVr3YSqJaupmoy1KjGqtf6qdKPDL1Mmq01URCFym1pmi+58ftME=
  file: build/*/*.tar.gz
  skip_cleanup: true
  on:
    repo: shimmerglass/ccmd
    tags: true
